version: "2"

services:
  web:
    build: ./docker-lib-wordpress/apache
    image: wordpress
    links:
     - mysql
    environment:
     - WORDPRESS_DB_HOST=mysql
     - WORDPRESS_DB_PASSWORD=password
    ports:
     - "192.168.11.101:80:80"
    volumes:
     - ./WordPress:/var/www/html
  mysql:
    image: mysql:5.7
    environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE=wordpress
